#!/usr/bin/env python
"""Robustness check: does the gender-story company ranking survive masking
sentences that contain explicit gender terms or personal names?

Motivation (Becca, 2026-07-28): names are gendered words — "Eric" scores like
"he" — and press-release quotes of named executives dominate some companies'
per-sentence extremes (Anduril especially). The published company numbers
include those sentences; this check recomputes them without.

Two masks, increasing severity, both reported:
  gendered   — the genre-analysis GENDERED regex (pronouns + gender terms)
  +names     — additionally drops likely person-name sentences: 2+ consecutive
               mid-sentence capitalized tokens ("Palmer Luckey", "Chief
               Strategy Officer Chris Brose"), Name-initial patterns
               ("Junho C."), and paired given names ("Eric and Karim").
               Deliberately over-broad (also catches "Air Force", "New York"):
               if the ranking survives aggressive masking, it is not
               name-driven.

The frozen baseline (mu/sd) is unchanged — only company sentence sets shrink.
Read-only: prints a report, writes docs/gender-mask-check.md, touches no
story data.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import numpy as np

from lowork.config import WEB_DATA_DIR
from lowork.embeddings import EmbeddingStore
from lowork.gender_axis import NEUTRAL_BAND, build_axis, project

from track_culture_propagation import company_sentences

GENDERED = re.compile(
    r"\b(man|men|woman|women|he|she|him|her|hers|his|himself|herself|male|female|"
    r"boys?|girls?|fathers?|mothers?|sons?|daughters?|dads?|moms?|brothers?|sisters?|"
    r"husbands?|wives|wife|kings?|queens?|gender|maternity|paternity|lgbtq?\+?|"
    r"boyfriends?|girlfriends?|alumnae|latinas?)\b", re.I)

CAP = r"[A-Z][a-z]+"
NAMEY = re.compile(
    rf"(?<!^)(?<![.!?] )\b{CAP} {CAP}\b"      # mid-sentence capitalized run
    rf"|\b{CAP} [A-Z]\."                      # "Junho C."
    rf"|\b{CAP} and {CAP}\b"                  # "Eric and Karim"
)


def masked_stats(sents: list[str], keep: list[bool], store, axis, mu, sd):
    kept = [s for s, k in zip(sents, keep) if k]
    if not kept:
        return None
    z = (project(store, axis, kept) - mu) / sd
    return {"n": len(kept),
            "mascPct": round(100 * float((z >= NEUTRAL_BAND).mean())),
            "femPct": round(100 * float((z <= -NEUTRAL_BAND).mean())),
            "meanZ": round(float(z.mean()), 2)}


def spearman(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    ra = np.argsort(np.argsort(a)).astype(float)
    rb = np.argsort(np.argsort(b)).astype(float)
    ra -= ra.mean(); rb -= rb.mean()
    return float((ra @ rb) / np.sqrt((ra @ ra) * (rb @ rb)))


def main():
    story = json.loads((WEB_DATA_DIR / "stories" / "gender-language.json").read_text())
    mu, sd = story["mu"], story["sd"]
    store = EmbeddingStore()
    axis = build_axis(store)

    rows = []
    for col in story["columns"]:
        co = col["company"]
        seen: dict[str, str] = {}
        for y, s in company_sentences(co, english_only=True):
            k = s.lower().strip()
            if k not in seen:
                seen[k] = s
        sents = list(seen.values())
        g_keep = [not GENDERED.search(s) for s in sents]
        gn_keep = [k and not NAMEY.search(s) for s, k in zip(sents, g_keep)]
        rows.append({
            "company": col["name"], "full": {"n": col["n"], "mascPct": col["mascPct"],
                                             "femPct": col["femPct"], "meanZ": col["meanZ"]},
            "gendered": masked_stats(sents, g_keep, store, axis, mu, sd),
            "names": masked_stats(sents, gn_keep, store, axis, mu, sd),
        })

    lines = [
        "# Name/gender-term masking robustness check",
        "",
        "Generated by scripts/gender_mask_check.py (read-only; published data",
        "untouched). Frozen baseline mu/sd unchanged. '+names' mask is",
        "deliberately over-broad — surviving it means the ranking is not",
        "name-driven.",
        "",
        "| company | full n | full masc% | gendered-masked masc% (n) | +names masc% (n) | full meanZ | +names meanZ |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda r: -r["full"]["mascPct"]):
        f, g, n = r["full"], r["gendered"], r["names"]
        lines.append(
            f"| {r['company']} | {f['n']} | {f['mascPct']} | {g['mascPct']} ({g['n']}) | "
            f"{n['mascPct']} ({n['n']}) | {f['meanZ']:+.2f} | {n['meanZ']:+.2f} |")

    for key in ("mascPct", "meanZ"):
        full = [r["full"][key] for r in rows]
        lines += ["", f"Spearman rank agreement on {key}: "
                  f"gendered-masked {spearman(full, [r['gendered'][key] for r in rows]):.3f}, "
                  f"+names {spearman(full, [r['names'][key] for r in rows]):.3f}"]

    biggest = sorted(rows, key=lambda r: -abs(r["full"]["mascPct"] - r["names"]["mascPct"]))[:5]
    lines += ["", "Largest masc% movers under +names masking: " +
              ", ".join(f"{r['company']} {r['full']['mascPct']}→{r['names']['mascPct']}"
                        for r in biggest), ""]
    memo = "\n".join(lines)
    out = Path(__file__).resolve().parent.parent / "docs" / "gender-mask-check.md"
    out.write_text(memo)
    print(memo)
    print(f"Wrote {out}")


if __name__ == "__main__":
    argparse.ArgumentParser(description=__doc__).parse_args()
    main()
